// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyjI3Gk_2Pg24RRvP0_lK2An6FFv2Bzo',
    appId: '1:839361097161:web:698c60fb22e35c8aa18c18',
    messagingSenderId: '839361097161',
    projectId: 'firebase-bloc-ecommerce02',
    authDomain: 'fir-bloc-ecommerce02.firebaseapp.com',
    storageBucket: 'firebase-bloc-ecommerce02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRTr2pnY7soSplKOEzlycRQKwydUTpfk',
    appId: '1:839361097161:android:9b18775138d50c0ca18c18',
    messagingSenderId: '839361097161',
    projectId: 'firebase-bloc-ecommerce02',
    storageBucket: 'firebase-bloc-ecommerce02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwS8jv7amWgggFuBjIEoJ6nH_vnoPG1jg',
    appId: '1:839361097161:ios:6fc417c5d8518e76a18c18',
    messagingSenderId: '839361097161',
    projectId: 'firebase-bloc-ecommerce02',
    storageBucket: 'firebase-bloc-ecommerce02.appspot.com',
    iosClientId: '839361097161-46qkfktucnvqp57r460jghq9530ma08a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBlocEcommerce',
  );
}
